version: '3'

services:
  jekyll:
    image: jekyll/jekyll
    container_name: resume
    command: jekyll serve --watch --force_polling --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./entrypoint:/usr/jekyll/bin/entrypoint
      - ./:/srv/jekyll
